project_name: rediary
builds:
  - main: ./cmd/rediary/
    binary: rediary
    id: default
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

nfpms:
  - maintainer: aceberg <aceberg_a@proton.me>
    description: Emotional resource diary 
    homepage: https://github.com/aceberg/rediary
    license: MIT
    formats:
    - deb
    - rpm
    - apk
    - archlinux
    - termux.deb
    dependencies:
    - arp-scan

archives:
  - files:
    - LICENSE
    - README.md
    - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
