project_name: rediary
builds:
  - main: ./cmd/rediary/
    binary: rediary
    id: default
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm

nfpms:
  - maintainer: aceberg <aceberg_a@proton.me>
    description: Emotional resource diary 
    homepage: https://github.com/aceberg/rediary
    license: MIT
    section: utils
    formats:
    - deb
    - rpm
    - apk
    - archlinux
    - termux.deb
    dependencies:
    - arp-scan
    contents:
    - src: ./configs/rediary@.service
      dst: /lib/systemd/system/rediary@.service
    - src: ./configs/rediary.service
      dst: /lib/systemd/system/rediary.service
    scripts:
      postinstall: ./configs/postinstall.sh

archives:
  - files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    - ./configs/rediary@.service
    - ./configs/rediary.service
    - ./configs/install.sh

checksum:
  name_template: "checksums.txt"
