project_name: rediary
builds:
  - main: ./cmd/rediary/
    binary: rediary
    id: default
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
# dockers:
# - image_templates: ["ghcr.io/goreleaser/example:{{ .Version }}"]
#   dockerfile: Dockerfile
#   build_flag_templates:
#   - --label=org.opencontainers.image.title={{ .ProjectName }}
#   - --label=org.opencontainers.image.description={{ .ProjectName }}
#   - --label=org.opencontainers.image.url=https://github.com/goreleaser/example
#   - --label=org.opencontainers.image.source=https://github.com/goreleaser/example
#   - --label=org.opencontainers.image.version={{ .Version }}
#   - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#   - --label=org.opencontainers.image.revision={{ .FullCommit }}
#   - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: aceberg <aceberg_a@proton.me>
  description: Emotional resource diary 
  homepage: https://github.com/aceberg/rediary
  license: MIT
  formats:
  - deb
  - rpm
  - apk
